AllCops:
  NewCops: enable
  Exclude:
    - 'app/models/svgpath/**/*'

Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 120

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/BlockLength:
  CountAsOne: ['array', 'hash', 'heredoc']
