AllCops:
  NewCops: enable
  Exclude:
    - 'app/models/svgpath/**/*'

Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/BlockLength:
  CountAsOne: ['array', 'hash', 'heredoc']
