AllCops:
  NewCops: enable
  Exclude:
    - 'app/models/svgpath/**/*'

Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 120

Metrics/BlockLength:
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
