# Google Cloud configuration
# Documentation:
# - https://cloud.google.com/appengine/docs/standard/reference/app-yaml?tab=ruby#top
# - https://cloud.google.com/functions/docs/runtime-support#ruby

runtime: ruby32

entrypoint: bundle exec rackup -p $PORT

handlers:
- url: /.*
  script: auto
  secure: always
