name: Rubocop

on:
  push:
    paths:
      - 'app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@f20f1eae726df008313d2e0d78c5e602562a1bcf
      with:
        ruby-version: 2.7.8
    - name: Install dependencies
      run: bundle install
    - name: Run Rubocop
      run: bundle exec rubocop
